version: '3.8'

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  jaeger:
    image: jaegertracing/all-in-one:1.54
    ports:
      - "16686:16686"   # Jaeger UI
      - "4318:4318"     # OTLP HTTP receiver

  main-service:
    build: ./main-service
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - jaeger

  provider-service:
    build: ./provider-service
    depends_on:
      - main-service
    
